version: '3.2'
services:
  db:
    build: ./docker/db
    container_name: pizza_od-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./docker/db/database:/var/lib/mysql
      - ./docker/db/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
#    security_opt:
#      - seccomp:unconfined
    networks:
      pizza_od-network:

  web:
    build: ./docker/web
    container_name: pizza_od-web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/web/apache.ports.conf:/etc/apache2/ports.conf
      - ./docker/web/apache.default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - '8001:8001'
      - '8002:8002'
    depends_on:
      - db
    networks:
      pizza_od-network:

  phpmyadmin:
    build: ./docker/phpmyadmin
    container_name: pizza_od-phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - '8060:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      pizza_od-network:

  nginx:
    build: ./docker/nginx
    container_name: pizza_od-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.local.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
    networks:
      pizza_od-network:
    ports:
      - 80:80

networks:
  pizza_od-network:
    driver: bridge